/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AddCurrencyModal: typeof import('./src/components/AddCurrencyModal.vue')['default']
    AddTimezoneModal: typeof import('./src/components/AddTimezoneModal.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BackgroundPanel: typeof import('./src/components/BackgroundPanel.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LocalesCard: typeof import('./src/components/LocalesCard.vue')['default']
    ModalEditCurrency: typeof import('./src/components/RatesCard/ModalEditCurrency.vue')['default']
    Panels: typeof import('./src/components/Panels/Panels.vue')['default']
    RateHistoryChart: typeof import('./src/components/RateHistoryChart.vue')['default']
    RatesCard: typeof import('./src/components/RatesCard/index.vue')['default']
    SearchModal: typeof import('./src/components/SearchModal.vue')['default']
    SwapyPanelCurrencies: typeof import('./src/components/Panels/components/SwapyPanelCurrencies.vue')['default']
    SwapyPanelLocales: typeof import('./src/components/Panels/components/SwapyPanelLocales.vue')['default']
  }
}
