/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AddCurrencyModal: typeof import('./src/components/AddCurrencyModal.vue')['default']
    AddTimezoneModal: typeof import('./src/components/AddTimezoneModal.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    BackgroundPanel: typeof import('./src/components/BackgroundPanel.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Holographic: typeof import('./src/components/Holographic.vue')['default']
    LiquidGlassContainer: typeof import('./src/components/LiquidGlassContainer.vue')['default']
    LocalesCard: typeof import('./src/components/LocalesCard.vue')['default']
    RateHistoryChart: typeof import('./src/components/RateHistoryChart.vue')['default']
    RatesCard: typeof import('./src/components/RatesCard.vue')['default']
    SearchModal: typeof import('./src/components/SearchModal.vue')['default']
    SwapyPanelCurrencies: typeof import('./src/components/SwapyPanelCurrencies.vue')['default']
    SwapyPanelLocales: typeof import('./src/components/SwapyPanelLocales.vue')['default']
  }
}
